# Generated by Django 6.1.1 on 2026-09-10 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('CARDIOLOGY', 'Cardiology'), ('DERMATOLOGY', 'Dermatology'), ('PEDIATRICS', 'Pediatrics'), ('NEUROLOGY', 'Neurology'), ('ORTHOPEDICS', 'Orthopedics'), ('GYNECOLOGY', 'Gynecology'), ('GENERAL_MEDICINE', 'General Medicine'), ('ENT', 'ENT'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('DENTISTRY', 'Dentistry')], max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.CharField(max_length=100)),
                ('available_time_start', models.TimeField()),
                ('available_time_end', models.TimeField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
